- name: ensure openssh-server is present
  apt:
    pkg: openssh-server
    state: latest
    install_recommends: no
    force: yes
  notify: restart sshd

- name: register openssh-server version
  shell: 'dpkg -s openssh-server | grep "^Version" | sed -re "s/^.*:([0-9]+\.[0-9]+).*/\1/"'
  register: openssh_version
  always_run: true
  changed_when: false

- name: ensure ed25519 host key is present
  command: ssh-keygen -q -t ed25519 -N "" -f ssh_host_ed25519_key
  args:
    chdir: /etc/ssh
    creates: /etc/ssh/ssh_host_ed25519_key
  when: openssh_version.stdout | version_compare('6.5', '>=')

- name: determine if ed25519 host key exists
  stat:
    path: /etc/ssh/ssh_host_ed25519_key
  register: ed25519_key
  always_run: true

- name: ensure openssh config is latest
  template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
  notify: restart sshd

- name: ensure sftp chroot group is present
  group:
    name: "{{ sshd_sftp_chroot_group }}"
  when: sshd_sftp_chroot == 'yes'
