---

- name: ensure openssh-server is present
  apt:
    pkg: openssh-server
    state: present
    install_recommends: no
    force: yes
  notify: restart sshd

- name: ensure host keys are present
  command: "ssh-keygen -q -f ssh_host_{{ item }}_key -N '' -t {{ item }}"
  args:
    chdir: /etc/ssh
    creates: "/etc/ssh/ssh_host_{{ item }}_key"
  with_items: "{{ sshd_host_keys }}"

- name: ensure openssh config is latest
  template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
  notify: restart sshd

- name: ensure sftp chroot group is present
  group:
    name: "{{ sshd_sftp_chroot_group }}"
  when: sshd_sftp_chroot == 'yes'

- name: ensure authorized_keys dir exists
  file:
    path: /etc/ssh/authorized_keys
    state: directory
    owner: root
    group: root
    mode: 0755
  when: sshd_authorized_keys_file == "/etc/ssh/authorized_keys/%u"

- name: configure authorized keys
  authorized_key:
    user: "{{ item.user }}"
    key: "{{ item.key if item.key is string else '\n'.join(item.key) }}"
    path: "/etc/ssh/authorized_keys/{{ item.user }}"
    exclusive: true
    manage_dir: false
  loop: "{{ sshd_authorized_keys | flatten(levels=1) }}"
  when: sshd_authorized_keys_file == "/etc/ssh/authorized_keys/%u"
