---
driver:
  name: vagrant
  provider:
    name: virtualbox
platforms:
  - name: stretch64
    box: debian/stretch64
  - name: buster64
    box: debian/buster64
lint: |
  set -e
  yamllint .
  ansible-lint --exclude molecule/default/tests
provisioner:
  name: ansible
  become: true
verifier:
  name: goss
